//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCommon.Domain
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/WcfCommon.Domain")]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WcfCommon.Domain")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid CityIdField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private string LastNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRegistrationService")]
public interface IRegistrationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/GetCities", ReplyAction="http://tempuri.org/IRegistrationService/GetCitiesResponse")]
    WcfCommon.Domain.City[] GetCities(string term);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/GetCities", ReplyAction="http://tempuri.org/IRegistrationService/GetCitiesResponse")]
    System.Threading.Tasks.Task<WcfCommon.Domain.City[]> GetCitiesAsync(string term);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/AddUser", ReplyAction="http://tempuri.org/IRegistrationService/AddUserResponse")]
    void AddUser(WcfCommon.Domain.User composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/AddUser", ReplyAction="http://tempuri.org/IRegistrationService/AddUserResponse")]
    System.Threading.Tasks.Task AddUserAsync(WcfCommon.Domain.User composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRegistrationServiceChannel : IRegistrationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RegistrationServiceClient : System.ServiceModel.ClientBase<IRegistrationService>, IRegistrationService
{
    
    public RegistrationServiceClient()
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfCommon.Domain.City[] GetCities(string term)
    {
        return base.Channel.GetCities(term);
    }
    
    public System.Threading.Tasks.Task<WcfCommon.Domain.City[]> GetCitiesAsync(string term)
    {
        return base.Channel.GetCitiesAsync(term);
    }
    
    public void AddUser(WcfCommon.Domain.User composite)
    {
        base.Channel.AddUser(composite);
    }
    
    public System.Threading.Tasks.Task AddUserAsync(WcfCommon.Domain.User composite)
    {
        return base.Channel.AddUserAsync(composite);
    }
}
